public class Datetime_Assignment {
    public void diffofdate(){
        Date varTomorrowDate = Date.newInstance(2022,07,16);
        Date varTodaysDate = Date.newInstance(2022,07,15);
        integer dif = varTomorrowDate.daysBetween(varTodaysDate);
        system.debug('difference between two days is ' + dif);
    }

    public void Timecheck(){
        Datetime varTomorrowDatetime = Datetime.newInstance(2022, 07, 16, 7, 0, 0);
        Datetime var10DaysDatetime = Datetime.newInstance(2022, 07, 26, 7, 0, 0;
        
        long longdate = 12339874361L;
        datetime 7daysLater = varTomorrowDatetime.addDays(7);
        system.debug(7daysLater);
   
        }
    }


