public class PrimitiveDataTypeDemo2 {
    public void print1(){
        ID id1 = '0018Z00002f80iVQAQ';
        system.debug('print id = '+ id1);

        //Object is a parent class to all primitive data
        Object obj1 = 'this is a string';
        Object obj2 = 15;
        Object obj3 = true;
        system.debug('obj1 = '+ obj1);
        system.debug('obj2 = '+ obj2);
        system.debug('obj3 = '+ obj3);
     
    }
}
